[package]
name = "rcli"
version = "0.1.0"
authors = ["Ignis <joyforever@aliyun.com>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
